CREATE TABLE CLIENTE (
    IDCLI integer  NOT NULL,
    NOMCLIE varchar2(50)  NOT NULL,
    APECLIE varchar2(50)  NOT NULL,
    DOCCLIE char(8)  NOT NULL,
    EMACLIE varchar2(50)  NOT NULL,
    CELCLIE char(9)  NOT NULL,
    ESTCLIE char(1)  NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY (IDCLI)
) ;

CREATE TABLE MOTOS (
    IDMOT integer  NOT NULL,
    CATMOT varchar2(50)  NOT NULL,
    MARMOT varchar2(50)  NOT NULL,
    MODMOT varchar2(50)  NOT NULL,
    COLMOT varchar2(50)  NOT NULL,
    PRECOMMOT number(18,2)  NOT NULL,
    PREVENMOT number(18,2)  NOT NULL,
    GARMOT varchar2(20)  NOT NULL,
    STOCK integer  NOT NULL,
    ESTMOT char(1)  NOT NULL,
    CONSTRAINT MOTOS_pk PRIMARY KEY (IDMOT)
) ;

CREATE TABLE VENTA (
    IDVEN integer  NOT NULL,
    FECVEN date  NOT NULL,
    FOR_PAG varchar2(50) NOT NULL,
    IDCLI integer  NOT NULL,
    IDEMP integer  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (IDVEN)
) ;

CREATE TABLE VENTA_DETALLE (
    IDVENDET integer  NOT NULL,
    CANTVENDET integer  NOT NULL,
    IDVENT integer  NOT NULL,
    IDMOT int NOT NULL,
    IDREP int NOT NULL,
    CONSTRAINT VENTA_DETALLE_pk PRIMARY KEY (IDVENDET)
) ;

CREATE SEQUENCE INC_CLI
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_MOT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_VEN
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_VENDET
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRG_INC_CLI
  BEFORE INSERT ON CLIENTE 
  FOR EACH ROW
  BEGIN
    SELECT INC_CLI.NEXTVAL INTO :NEW.IDCLI FROM DUAL;
  END;
  /

      CREATE TRIGGER TRG_INC_MOT
  BEFORE INSERT ON MOTOS
  FOR EACH ROW
  BEGIN
    SELECT INC_MOT.NEXTVAL INTO :NEW.IDMOT FROM DUAL;
  END;
  /
          CREATE TRIGGER TRG_INC_VEN
  BEFORE INSERT ON VENTA
  FOR EACH ROW
  BEGIN
    SELECT INC_VEN.NEXTVAL INTO :NEW.IDVEN FROM DUAL;
  END;
  /
            CREATE TRIGGER TRG_INC_VENDET
  BEFORE INSERT ON VENTA_DETALLE
  FOR EACH ROW
  BEGIN
    SELECT INC_VENDET.NEXTVAL INTO :NEW.IDVENDET FROM DUAL;
  END;
  /
  

  INSERT ALL
       INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Miguel','Gutierrez','78452169','miguel@gmail.com','995687412','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Jose','Sivera','14256985','jose@gmail.com','992666961','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Mario','Quispe','74200697','mario@gmail.com','992693446','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Alberto','Manriquez','54582145','alberto@gmail.com','992857425','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Maria','Aribe','15423514','maria@gmail.com','993797613','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Abel','Sanchez','15426385','abel@gmail.com','992668960','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Antonio','Sánchez','21563100','antonio@gmail.com','910559418','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Maribel','Rodriguez','97582145','maribel@gmail.com','98225631','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Albel','Rodriguez','25468236','albel@gmail.com','993621458','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Marios','Conilla','26854796','marios@gmail.com','994562352','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Aladin','Castro','75866927','aladin@gmail.com','965985459','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Juan','Quispe','77656696','juan@gmail.com','96577418','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Naomi','Manriquez','78466660','naomi@gmail.com','954789455','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Jesus','Carnica','73266960','jesus@gmail.com','965871452','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Carlos','Sanchez','75668960','carlos@gmail.com','967412785','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Mishell','Palomino','79785690','mishell@gmail.com','995612478','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Juana','Malazquez','71266960','juana@gmail.com','974826986','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Adolfo','Manrique','78956412','adolfo@gmail.com','923654178','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Martha','Rodriguez','73456960','martha@gmail.com','969651227','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Adolfo','Meneses','76254960','adolfo@gmail.com','966298785','A')
       SELECT * FROM DUAL
COMMIT;   

 

INSERT ALL
       INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Yamaha', 'ML-58741', 'azul', '2 años','60', '12059,00','15000,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Suzuki', 'J-84329', 'verde', '1 años','30', '11450,00','16541,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Yamaha', 'MT-07 2021-2022', 'azul', '2 años','100', '11059,00','15059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Suzuki', 'G-85529', 'negro', '1 años','50', '12550,00','17059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Aprilia', 'L-20186', 'azul', '2 años','82', '15789,00','20059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Ducati', 'L-20189', 'Amarillo', '2 años','40', '13859,00','18059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Honda', 'L-20205', 'azul', '2 años','100', '10859,00','15059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Cagiva', 'G-85528', 'negro', '1 años','50', '20550,00','22059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Suzuki', 'L-20187', 'azul', '2 años','82', '12789,00','15059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Yamaha', 'MT-07 2018-2020', 'Amarillo', '2 años','40', '11859,00','16059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Puma', 'MF-58741', 'azul', '2 años','60', '12059,00','15000,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Generico', 'JF-84329', 'verde', '1 años','30', '11450,00','16541,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Puma', 'MTH-07 2021-2022', 'azul', '2 años','100', '11059,00','15059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Torito', 'GH-85529', 'negro', '1 años','50', '12550,00','17059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Puma', 'LQ-20186', 'azul', '2 años','82', '15789,00','20059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Ballay', 'LQ-20189', 'Amarillo', '2 años','40', '13859,00','18059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Honda', 'LT-20205', 'azul', '2 años','100', '10859,00','15059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Honda', 'GT-85529', 'negro', '1 años','50', '20440,00','22999,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Suzuki', 'LI-20186', 'azul', '2 años','82', '12889,00','15159,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Yamaha', 'MIT-07 2018-2020', 'Amarillo', '2 años','40', '12059,00','17859,00','A')
        SELECT * FROM DUAL
COMMIT;


ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES CLIENTE (IDCLI);

    ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_MOTOS
    FOREIGN KEY (IDMOT)
    REFERENCES MOTOS (IDMOT);

ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (IDVENT)
    REFERENCES VENTA (IDVEN);

 
INSERT ALL
       INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES ('02/05/22','Efectivo', '2', '2')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('02/05/22','YAPE', '1', '6')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('03/05/22','Efectivo', '4', '5')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('03/05/22','Bin', '5', '5')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('04/05/22','Efectivo', '3', '2')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('04/05/22','YAPE', '4', '6')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('04/05/22','Efectivo', '5', '5')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('05/05/22','Bin', '6', '5')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('05/05/22','Efectivo', '7', '2')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('05/05/22','YAPE', '8', '6')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('06/05/22','Efectivo', '9', '5')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('06/05/22','Bin', '11', '5')
       SELECT * FROM DUAL
COMMIT;  

INSERT ALL
       INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('2','1', '10', '2')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','2', '11', '3')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','3', '12', '4')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','4', '13', '2')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('2','5', '14', '2')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','6', '15', '3')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','7', '16', '4')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','8', '9', '2')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('2','9', '17', '2')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','10', '18', '3')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','11', '19', '4')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','12', '20', '2')
       SELECT * FROM DUAL
COMMIT;  
  
